services:
  - type: web
    name: franquicias-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: SERVER_PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
